#!/bin/sh

set -eu

me="${0##*/}"
default_expiry='1w'
storage_url='https://file.io'
expires_parameter='expires'

if [ $# -lt 1 ]; then
	echo "Usage: $me file ..." 1>&2
	exit 1
fi

# TODO: put somewhere other than /tmp by default

# BSD
if mktemp -d -u -t "$me" >/dev/null 2>&1; then
	tmpdir=$(mktemp -d -t "$me")
# GNU coreutils
elif mktemp -d -u -p "${TMPDIR:-/tmp}" "${me}.XXXXXXXXXX" >/dev/null 2>&1; then
	tmpdir=$(mktemp -d -p "${TMPDIR:-/tmp}" "${me}.XXXXXXXXXX")
else
	echo 'Unable to figure out how to make a temporary directory. Aborting.' 1>&2
	exit 1
fi
trap 'rm -rf "$tmpdir"' EXIT

archive_basename="$(uuidgen)"
7z a -m0=lzma2 -p -mhe=on -v2g "${tmpdir}/$archive_basename" "$@"

cd "$tmpdir"
echo

if [ ! -f "${archive_basename}.7z.002" ]; then
	mv "${archive_basename}.7z.001" "${archive_basename}.7z"
	files="${archive_basename}.7z"
else
	files="${archive_basename}.7z.*"
fi

for f in $files; do
	for t in 1 2 3 4 5 6; do
		response="$(curl -F "file=@${f}" "${storage_url}/?${expires_parameter}=${default_expiry}")" && break
		test $t -eq 6 || echo "Upload failed, retrying: ${t}/5" 1>&2
	done
	if [ $? -gt 0 ]; then
		echo 'Aborting after 5 attempts.' 1>&2
		exit 1
	fi
	urls="${urls:-}$(echo "$response" | jq -r '.link') "
	expiry="$(echo "$response" | jq -r '.expiry')"
done

echo
for url in $urls; do
	echo "URL:    $url"
done
echo "Expiry: $expiry"
